version: '3.8'

services:
  app:
    # Для работы USB
    privileged: true

    # Путь до Dockerfile
    build:
      context: ./
      dockerfile: ./Dockerfile

    # Имя для создаваемого контейнера
    container_name: serial-io


    # Перезапускаем сервис в случае падения
    restart: on-failure

    # Прокладывам путь для файлов. Все файлы, которые хранятся у вас в 
    # директории ./app, появятся в корне контейнера /
    volumes:
      - .:/app

    # Опасно! прокидываем ВСЕ /dev устройства в контейнер
    # Оказалось не надо. втф?
    devices:
      # - /dev:/dev
      # - "COM4:/dev/ttyS3" # Попытка прокинуть порт винды в докер

    # Создание переменных окружения в контейнере (из файла .env)
    env_file:
      - ./.env

    # gunicorn запускает в файле main.py, функцию run_app_production с конфигом gunicorn.conf.py
    command: python main.py -b

